[window]
size=[800,500]
title="TRgame"
icontitle="HELLO?"
icon="icon.png"
fullscreen=1
fullsize = ['default', 'default']
noResolution = false                ####
noWarning = false
joystick = false#æ‰‹æŸ„ğŸ®

[test]
test1=false
test2=false
#åˆ«æ”¹

[game]
const="const.json"
FPS = 60
tick=20
rectick=60
randomtickspeed = 100
seed="random"
mousespeed=1
cameraspeed=50
holval=1.2
bg=[150,220,150]
vsync=1
depth=0

maxelsecount = 500
pondmaxdis=5000
maxpondcount = 10000
maxfriendcount=1500

renderdistance=2000
renderdistancetoscreen=false

[message]
deathmessage="ä½ å¤±è´¥äº†ï¼"
pausemessage="æ¸¸æˆæš‚åœï¼"
waitmessage="ç§»åŠ¨é¼ æ ‡å¼€å§‹æ¸¸æˆï¼"

[senior]
blocksize=512  # åŒºå—å¤§å°
